#include <ctype.h>
#include <stdio.h>

/* character classes */
#define LETTER 0
#define DIGIT 1
#define UNKNOWN 99

/* token codes */
#define INT_LIT 10
#define IDENT 11
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26

/* Global variables */
int nextToken;

/* Function prototypes */
void expr();
void term();
void factor();
void lex();
void error();

/* Function to simulate lexical analysis */
void lex() {
    /* Simulated lexical analysis to set nextToken */
}

/* Error function */
void error() {
    printf("Error occurred!\n");
}

/* expr
Parses strings in the language generated by the rule:
<expr> -> <term> {(+ | -) <term>}
*/
void expr() {
    printf("[expr\n");
    /* Parse the first term */
    term();
    /* As long as the next token is + or -, get
    the next token and parse the next term */
    while (nextToken == '+' || nextToken == '-') {
        lex();
        term();
    }
    printf("]\n");
}

/* term
Parses strings in the language generated by the rule:
<term> -> <factor> {(* | /) <factor>)
*/
void term() {
    printf("[term\n");
    /* Parse the first factor */
    factor();
    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == '*' || nextToken == '/') {
        lex();
        factor();
    }
    printf("]\n");
}

/* factor
Parses strings in the language generated by the rule:
<factor> -> id | int_constant | ( <expr )
*/
void factor() {
    printf("[factor\n");
    /* Determine which RHS */
    if (nextToken == IDENT || nextToken == INT_LIT) {
        /* Get the next token */
        lex();
    } else {
        if (nextToken == '(') {
            lex();
            expr();
            if (nextToken == ')') {
                lex();
            } else {
                error();
            }
        } else {
            error();
        }
    }
    printf("]\n");
}

/* Main function */
int main() {
    /* Initialize nextToken with the first token */
    nextToken = /* Initialize with the first token */;
    /* Call the expr function to start parsing */
    expr();
    return 0;
}